# Generated by Django 4.1.2 on 2022-10-06 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Petrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default=1, max_length=2)),
                ('price', models.FloatField(default=0, max_length=(15, 2))),
                ('delete_flag', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('volume', models.FloatField(default=0, max_length=(15, 2))),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('petrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppmsapp.petrol')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=250)),
                ('volume', models.FloatField(default=0, max_length=(15, 2))),
                ('price', models.FloatField(default=0, max_length=(15, 2))),
                ('amount', models.FloatField(default=0, max_length=(15, 2))),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('petrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppmsapp.petrol')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=60)),
                ('r_DOB', models.DateField()),
                ('r_details', models.CharField(max_length=500)),
                ('r_quantity', models.IntegerField(null=True)),
                ('r_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppmsapp.category')),
                ('r_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_req', models.CharField(max_length=50)),
                ('l_reason', models.CharField(max_length=100)),
                ('l_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_fname', models.CharField(max_length=30)),
                ('e_lname', models.CharField(max_length=30)),
                ('e_address', models.CharField(max_length=100)),
                ('e_age', models.IntegerField()),
                ('e_phone_numbr', models.BigIntegerField(verbose_name=10)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_post', models.CharField(max_length=20)),
                ('e_photo', models.ImageField(null=True, upload_to='image/')),
                ('e_shift', models.CharField(max_length=30)),
                ('e_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppmsapp.category')),
                ('e_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppmsapp.report')),
                ('e_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_attendnce', models.CharField(max_length=30)),
                ('a_DOB', models.DateField()),
                ('a_post', models.CharField(max_length=30)),
                ('a_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
